### PR TITLE
Hacktoberfest

### PR DESCRIPTION
**Pull request by 0xbn0xi0us**
Added Search engineering optimization description meta tag.

### CODE REVIEW

**Comment by 0xbn0xi0us** [comment]
It will give good impact on search engines.(please add as hacktoberfest and suggest issues if there is in my commit)

**Comment by proghead00** [comment]
@iamsuyashpatel07 I'm not merging a meta tag as a new pull request for Hacktoberfest. You can add new features, create responsiveness, and even add your own mini-project(s).

**Comment by 0xbn0xi0us** [comment]
Sir can you suggest any projects,so that I can work on it (on html,css and javascript).
I can make 
Javascript clock 
Javascript calculator

**Comment by proghead00** [comment]
You can try some non-mainstream ones maybe. TBH, I didn't think to make this repo open for contribution, rather, it was thought of to be a complete resource uploaded by myself.

**Pull request closed without merging**
